In [2]:
!pip install pandas_datareader
!pip install yfinance

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas_datareader
  Obtaining dependency information for pandas_datareader from https://files.pythonhosted.org/packages/3f/16/56c9d648b503619ebe96f726b5f642b68e299b34162ed2d6faa9d7966b7d/pandas_datareader-0.10.0-py3-none-any.whl.metadata
  Downloading pandas_datareader-0.10.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: lxml in c:\programdata\anaconda3\lib\site-packages (from pandas_datareader) (4.9.3)
Requirement already satisfied: pandas>=0.23 in c:\programdata\anaconda3\lib\site-packages (from pandas_datareader) (2.0.3)
Requirement already satisfied: requests>=2.19.0 in c:\programdata\anaconda3\lib\site-packages (from pandas_datareader) (2.31.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.23->pandas_datareader) (1.24.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2023.7.22)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.16.0)
Downloading pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
   ---------------------------------------- 0.0/109.5 kB ? eta -:--:--
   ------- ------------------------------- 20.5/109.5 kB 320.0 kB/s eta 0:00:01
   ------- ------------------------------- 20.5/109.5 kB 320.0 kB/s eta 0:00:01
   --------------------- ----------------- 61.4/109.5 kB 409.6 kB/s eta 0:00:01
   --------------------- ----------------- 61.4/109.5 kB 409.6 kB/s eta 0:00:01
   -------------------------------------- 109.5/109.5 kB 453.1 kB/s eta 0:00:00
Installing collected packages: pandas_datareader
Successfully installed pandas_datareader-0.10.0
Defaulting to user installation because normal site-packages is not writeable
Collecting yfinance
  Obtaining dependency information for yfinance from https://files.pythonhosted.org/packages/d5/b5/70bb98ee38ce532ee29fab76fb668382291fe6e1aa69a8c1ac7e6bc108e7/yfinance-0.2.38-py2.py3-none-any.whl.metadata
  Downloading yfinance-0.2.38-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.0.3)
Requirement already satisfied: numpy>=1.16.5 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (1.24.3)
Requirement already satisfied: requests>=2.31 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.31.0)
Collecting multitasking>=0.0.7 (from yfinance)
  Obtaining dependency information for multitasking>=0.0.7 from https://files.pythonhosted.org/packages/3e/8a/bb3160e76e844db9e69a413f055818969c8acade64e1a9ac5ce9dfdcf6c1/multitasking-0.0.11-py3-none-any.whl.metadata
  Downloading multitasking-0.0.11-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: lxml>=4.9.1 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (4.9.3)
Requirement already satisfied: appdirs>=1.4.4 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2023.3.post1)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.4.2.tar.gz (315 kB)
     ---------------------------------------- 0.0/315.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/315.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/315.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/315.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/315.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/315.3 kB ? eta -:--:--
     ----- ---------------------------------- 41.0/315.3 kB ? eta -:--:--
     ------- ------------------------------- 61.4/315.3 kB 1.1 MB/s eta 0:00:01
     ------- ------------------------------- 61.4/315.3 kB 1.1 MB/s eta 0:00:01
     -------- ---------------------------- 71.7/315.3 kB 558.5 kB/s eta 0:00:01
     -------- ---------------------------- 71.7/315.3 kB 558.5 kB/s eta 0:00:01
     ---------- -------------------------- 92.2/315.3 kB 348.6 kB/s eta 0:00:01
     ---------- -------------------------- 92.2/315.3 kB 348.6 kB/s eta 0:00:01
     ---------- -------------------------- 92.2/315.3 kB 348.6 kB/s eta 0:00:01
     ---------- -------------------------- 92.2/315.3 kB 348.6 kB/s eta 0:00:01
     ------------ ----------------------- 112.6/315.3 kB 251.6 kB/s eta 0:00:01
     ------------ ----------------------- 112.6/315.3 kB 251.6 kB/s eta 0:00:01
     ------------ ----------------------- 112.6/315.3 kB 251.6 kB/s eta 0:00:01
     ------------ ----------------------- 112.6/315.3 kB 251.6 kB/s eta 0:00:01
     ------------ ----------------------- 112.6/315.3 kB 251.6 kB/s eta 0:00:01
     -------------- --------------------- 122.9/315.3 kB 175.7 kB/s eta 0:00:02
     -------------- --------------------- 122.9/315.3 kB 175.7 kB/s eta 0:00:02
     -------------- --------------------- 122.9/315.3 kB 175.7 kB/s eta 0:00:02
     -------------- --------------------- 122.9/315.3 kB 175.7 kB/s eta 0:00:02
     -------------- --------------------- 122.9/315.3 kB 175.7 kB/s eta 0:00:02
     -------------- --------------------- 122.9/315.3 kB 175.7 kB/s eta 0:00:02
     ---------------- ------------------- 143.4/315.3 kB 141.9 kB/s eta 0:00:02
     ---------------- ------------------- 143.4/315.3 kB 141.9 kB/s eta 0:00:02
     ---------------- ------------------- 143.4/315.3 kB 141.9 kB/s eta 0:00:02
     ---------------- ------------------- 143.4/315.3 kB 141.9 kB/s eta 0:00:02
     ---------------- ------------------- 143.4/315.3 kB 141.9 kB/s eta 0:00:02
     ---------------- ------------------- 143.4/315.3 kB 141.9 kB/s eta 0:00:02
     ---------------- ------------------- 143.4/315.3 kB 141.9 kB/s eta 0:00:02
     ---------------- ------------------- 143.4/315.3 kB 141.9 kB/s eta 0:00:02
     ---------------- ------------------- 143.4/315.3 kB 141.9 kB/s eta 0:00:02
     ----------------- ------------------ 153.6/315.3 kB 108.0 kB/s eta 0:00:02
     ----------------- ------------------ 153.6/315.3 kB 108.0 kB/s eta 0:00:02
     ----------------- ------------------ 153.6/315.3 kB 108.0 kB/s eta 0:00:02
     ----------------- ------------------ 153.6/315.3 kB 108.0 kB/s eta 0:00:02
     ----------------- ------------------ 153.6/315.3 kB 108.0 kB/s eta 0:00:02
     ----------------- ------------------ 153.6/315.3 kB 108.0 kB/s eta 0:00:02
     ----------------- ------------------ 153.6/315.3 kB 108.0 kB/s eta 0:00:02
     -------------------- ---------------- 174.1/315.3 kB 99.8 kB/s eta 0:00:02
     -------------------- ---------------- 174.1/315.3 kB 99.8 kB/s eta 0:00:02
     -------------------- ---------------- 174.1/315.3 kB 99.8 kB/s eta 0:00:02
     ---------------------- ------------- 194.6/315.3 kB 102.6 kB/s eta 0:00:02
     ---------------------- ------------- 194.6/315.3 kB 102.6 kB/s eta 0:00:02
     ---------------------- ------------- 194.6/315.3 kB 102.6 kB/s eta 0:00:02
     ------------------------ ------------ 204.8/315.3 kB 99.6 kB/s eta 0:00:02
     ------------------------ ------------ 204.8/315.3 kB 99.6 kB/s eta 0:00:02
     ------------------------ ------------ 204.8/315.3 kB 99.6 kB/s eta 0:00:02
     ------------------------- ---------- 225.3/315.3 kB 103.5 kB/s eta 0:00:01
     ------------------------- ---------- 225.3/315.3 kB 103.5 kB/s eta 0:00:01
     ------------------------- ---------- 225.3/315.3 kB 103.5 kB/s eta 0:00:01
     ------------------------- ---------- 225.3/315.3 kB 103.5 kB/s eta 0:00:01
     --------------------------- --------- 235.5/315.3 kB 99.4 kB/s eta 0:00:01
     --------------------------- --------- 235.5/315.3 kB 99.4 kB/s eta 0:00:01
     --------------------------- --------- 235.5/315.3 kB 99.4 kB/s eta 0:00:01
     --------------------------- --------- 235.5/315.3 kB 99.4 kB/s eta 0:00:01
     --------------------------- --------- 235.5/315.3 kB 99.4 kB/s eta 0:00:01
     ------------------------------ ------ 256.0/315.3 kB 98.9 kB/s eta 0:00:01
     ------------------------------ ------ 256.0/315.3 kB 98.9 kB/s eta 0:00:01
     ------------------------------ ------ 256.0/315.3 kB 98.9 kB/s eta 0:00:01
     ------------------------------ ------ 256.0/315.3 kB 98.9 kB/s eta 0:00:01
     -------------------------------- ---- 276.5/315.3 kB 97.9 kB/s eta 0:00:01
     -------------------------------- ---- 276.5/315.3 kB 97.9 kB/s eta 0:00:01
     -------------------------------- ---- 276.5/315.3 kB 97.9 kB/s eta 0:00:01
     -------------------------------- ---- 276.5/315.3 kB 97.9 kB/s eta 0:00:01
     -------------------------------- ---- 276.5/315.3 kB 97.9 kB/s eta 0:00:01
     -------------------------------- ---- 276.5/315.3 kB 97.9 kB/s eta 0:00:01
     -------------------------------- ---- 276.5/315.3 kB 97.9 kB/s eta 0:00:01
     -------------------------------- ---- 276.5/315.3 kB 97.9 kB/s eta 0:00:01
     -------------------------------- ---- 276.5/315.3 kB 97.9 kB/s eta 0:00:01
     -------------------------------- ---- 276.5/315.3 kB 97.9 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     --------------------------------- --- 286.7/315.3 kB 87.6 kB/s eta 0:00:01
     ------------------------------------  307.2/315.3 kB 73.7 kB/s eta 0:00:01
     ------------------------------------  307.2/315.3 kB 73.7 kB/s eta 0:00:01
     ------------------------------------- 315.3/315.3 kB 73.7 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.17.3.tar.gz (3.0 MB)
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/3.0 MB 100.9 kB/s eta 0:00:29
     ---------------------------------------- 0.0/3.0 MB 100.9 kB/s eta 0:00:29
     ---------------------------------------- 0.0/3.0 MB 100.9 kB/s eta 0:00:29
     ---------------------------------------- 0.0/3.0 MB 100.9 kB/s eta 0:00:29
      --------------------------------------- 0.0/3.0 MB 75.7 kB/s eta 0:00:39
      --------------------------------------- 0.0/3.0 MB 75.7 kB/s eta 0:00:39
      --------------------------------------- 0.0/3.0 MB 75.7 kB/s eta 0:00:39
      --------------------------------------- 0.0/3.0 MB 75.7 kB/s eta 0:00:39
      --------------------------------------- 0.1/3.0 MB 84.1 kB/s eta 0:00:35
      --------------------------------------- 0.1/3.0 MB 84.1 kB/s eta 0:00:35
      --------------------------------------- 0.1/3.0 MB 84.1 kB/s eta 0:00:35
      --------------------------------------- 0.1/3.0 MB 84.1 kB/s eta 0:00:35
      --------------------------------------- 0.1/3.0 MB 77.1 kB/s eta 0:00:38
      --------------------------------------- 0.1/3.0 MB 77.1 kB/s eta 0:00:38
      --------------------------------------- 0.1/3.0 MB 77.1 kB/s eta 0:00:38
      --------------------------------------- 0.1/3.0 MB 77.1 kB/s eta 0:00:38
      --------------------------------------- 0.1/3.0 MB 77.1 kB/s eta 0:00:38
      --------------------------------------- 0.1/3.0 MB 77.1 kB/s eta 0:00:38
      --------------------------------------- 0.1/3.0 MB 77.1 kB/s eta 0:00:38
      --------------------------------------- 0.1/3.0 MB 77.1 kB/s eta 0:00:38
      --------------------------------------- 0.1/3.0 MB 77.1 kB/s eta 0:00:38
      --------------------------------------- 0.1/3.0 MB 77.1 kB/s eta 0:00:38
      --------------------------------------- 0.1/3.0 MB 77.1 kB/s eta 0:00:38
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 62.4 kB/s eta 0:00:46
     - -------------------------------------- 0.1/3.0 MB 55.0 kB/s eta 0:00:52
     - -------------------------------------- 0.1/3.0 MB 55.0 kB/s eta 0:00:52
     - -------------------------------------- 0.1/3.0 MB 55.0 kB/s eta 0:00:52
     - -------------------------------------- 0.1/3.0 MB 55.0 kB/s eta 0:00:52
     - -------------------------------------- 0.1/3.0 MB 55.0 kB/s eta 0:00:52
     - -------------------------------------- 0.1/3.0 MB 55.0 kB/s eta 0:00:52
     - -------------------------------------- 0.1/3.0 MB 52.1 kB/s eta 0:00:55
     - -------------------------------------- 0.1/3.0 MB 52.1 kB/s eta 0:00:55
     - -------------------------------------- 0.1/3.0 MB 52.1 kB/s eta 0:00:55
     - -------------------------------------- 0.1/3.0 MB 52.1 kB/s eta 0:00:55
     - -------------------------------------- 0.1/3.0 MB 52.1 kB/s eta 0:00:55
     - -------------------------------------- 0.1/3.0 MB 52.1 kB/s eta 0:00:55
     - -------------------------------------- 0.1/3.0 MB 52.1 kB/s eta 0:00:55
     - -------------------------------------- 0.1/3.0 MB 52.1 kB/s eta 0:00:55
     - -------------------------------------- 0.1/3.0 MB 48.7 kB/s eta 0:00:58
     - -------------------------------------- 0.1/3.0 MB 48.7 kB/s eta 0:00:58
     - -------------------------------------- 0.1/3.0 MB 48.7 kB/s eta 0:00:58
     - -------------------------------------- 0.1/3.0 MB 48.7 kB/s eta 0:00:58
     - -------------------------------------- 0.1/3.0 MB 48.7 kB/s eta 0:00:58
     - -------------------------------------- 0.1/3.0 MB 48.7 kB/s eta 0:00:58
     - -------------------------------------- 0.1/3.0 MB 48.7 kB/s eta 0:00:58
     - -------------------------------------- 0.1/3.0 MB 48.7 kB/s eta 0:00:58
     - -------------------------------------- 0.1/3.0 MB 48.7 kB/s eta 0:00:58
     - -------------------------------------- 0.1/3.0 MB 48.7 kB/s eta 0:00:58
     - -------------------------------------- 0.1/3.0 MB 48.7 kB/s eta 0:00:58
     - -------------------------------------- 0.1/3.0 MB 48.7 kB/s eta 0:00:58
     -- ------------------------------------- 0.2/3.0 MB 47.3 kB/s eta 0:01:00
     -- ------------------------------------- 0.2/3.0 MB 47.3 kB/s eta 0:01:00
     -- ------------------------------------- 0.2/3.0 MB 47.3 kB/s eta 0:01:00
     -- ------------------------------------- 0.2/3.0 MB 47.3 kB/s eta 0:01:00
     -- ------------------------------------- 0.2/3.0 MB 47.3 kB/s eta 0:01:00
     -- ------------------------------------- 0.2/3.0 MB 47.3 kB/s eta 0:01:00
     -- ------------------------------------- 0.2/3.0 MB 47.3 kB/s eta 0:01:00
     -- ------------------------------------- 0.2/3.0 MB 47.3 kB/s eta 0:01:00
     -- ------------------------------------- 0.2/3.0 MB 47.3 kB/s eta 0:01:00
     -- ------------------------------------- 0.2/3.0 MB 47.3 kB/s eta 0:01:00
     -- ------------------------------------- 0.2/3.0 MB 47.3 kB/s eta 0:01:00
     -- ------------------------------------- 0.2/3.0 MB 46.0 kB/s eta 0:01:01
     -- ------------------------------------- 0.2/3.0 MB 46.0 kB/s eta 0:01:01
     -- ------------------------------------- 0.2/3.0 MB 46.0 kB/s eta 0:01:01
     -- ------------------------------------- 0.2/3.0 MB 46.0 kB/s eta 0:01:01
     -- ------------------------------------- 0.2/3.0 MB 46.0 kB/s eta 0:01:01
     -- ------------------------------------- 0.2/3.0 MB 46.0 kB/s eta 0:01:01
     -- ------------------------------------- 0.2/3.0 MB 46.0 kB/s eta 0:01:01
     -- ------------------------------------- 0.2/3.0 MB 46.0 kB/s eta 0:01:01
     -- ------------------------------------- 0.2/3.0 MB 46.0 kB/s eta 0:01:01
     -- ------------------------------------- 0.2/3.0 MB 46.0 kB/s eta 0:01:01
     -- ------------------------------------- 0.2/3.0 MB 46.0 kB/s eta 0:01:01

  WARNING: The script sample.exe is installed in 'C:\Users\pc\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
import matplotlib.pyplot as plt

In [2]:
sec_data = pd.read_csv('PG_BEI.DE_2007_2017.csv', index_col='Date')

In [3]:
sec_data.tail()

                   PG     BEI.DE
Date
2017-03-17  89.605492  87.559509
2017-03-20  89.822121  87.440437
2017-03-21  89.792580  87.202278
2017-03-22  89.595642  86.983986
2017-03-23  89.379013  87.470207

In [4]:
sec_returns = np.log(sec_data / sec_data.shift(1))

In [5]:
sec_returns

                  PG    BEI.DE
Date
2007-01-03       NaN       NaN
2007-01-04 -0.007621  0.006545
2007-01-05 -0.008624 -0.020772
2007-01-08  0.002203  0.000202
2007-01-09 -0.002517 -0.022858
...              ...       ...
2017-03-17 -0.004824  0.004430
2017-03-20  0.002415 -0.001361
2017-03-21 -0.000329 -0.002727
2017-03-22 -0.002196 -0.002506
2017-03-23 -0.002421  0.005574

[2574 rows x 2 columns]

## PG

In [6]:
sec_returns['PG'].mean()

0.00025104897045418774

In [7]:
sec_returns['PG'].mean() * 250

0.06276224261354693

In [8]:
sec_returns['PG'].std()

0.011161903265721093

In [9]:
sec_returns['PG'].std() * 250 ** 0.5

0.17648518671075145

## Beiersdorf

In [10]:
sec_returns['BEI.DE'].mean()

0.00026921457170927

In [11]:
sec_returns['BEI.DE'].mean() * 250

0.0673036429273175

In [12]:
sec_returns['BEI.DE'].std()

0.014258683507114199

In [13]:
sec_returns['BEI.DE'].std() * 250 ** 0.5

0.22544958158979275

Final Results:

In [14]:
print(sec_returns['PG'].mean() * 250)
print(sec_returns['BEI.DE'].mean() * 250)

0.06276224261354693
0.0673036429273175

In [15]:
sec_returns[['PG', 'BEI.DE']].mean() * 250

PG        0.062762
BEI.DE    0.067304
dtype: float64

In [22]:
sec_returns[['PG', 'BEI.DE']].mean() * 250

PG        0.062762
BEI.DE    0.067304
dtype: float64

In [16]:
sec_returns[['PG', 'BEI.DE']].std() * 250 ** 0.5

PG        0.176485
BEI.DE    0.225450
dtype: float64