In [ ]:
!pip install pyEX
!pip install iexfinance

In [8]:
!pip install quandl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: quandl in c:\users\pc\appdata\roaming\python\python311\site-packages (3.7.0)
Requirement already satisfied: pandas>=0.14 in c:\programdata\anaconda3\lib\site-packages (from quandl) (2.0.3)
Requirement already satisfied: numpy>=1.8 in c:\programdata\anaconda3\lib\site-packages (from quandl) (1.24.3)
Requirement already satisfied: requests>=2.7.0 in c:\programdata\anaconda3\lib\site-packages (from quandl) (2.31.0)
Requirement already satisfied: inflection>=0.3.1 in c:\programdata\anaconda3\lib\site-packages (from quandl) (0.5.1)
Requirement already satisfied: python-dateutil in c:\programdata\anaconda3\lib\site-packages (from quandl) (2.8.2)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from quandl) (1.16.0)
Requirement already satisfied: more-itertools in c:\programdata\anaconda3\lib\site-packages (from quandl) (8.12.0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.14->quandl) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.14->quandl) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.7.0->quandl) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.7.0->quandl) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.7.0->quandl) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.7.0->quandl) (2023.7.22)

In [2]:
import numpy as np
from pandas_datareader import data as wb
import matplotlib.pyplot as plt

In [11]:
import quandl
quandl.ApiConfig.api_key = 'Wi5xJFnD9bwKLwazVpvm'
quandl.ApiConfig.verify_ssl = False

In [12]:
import quandl
data = quandl.get('NSE/OIL')

c:\ProgramData\anaconda3\Lib\site-packages\urllib3\connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.nasdaq.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

In [13]:
data

,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
Date,,,,,,,
2009-09-30,1096.00,1156.70,1090.00,1135.00,1141.20,19748012.0,223877.07
2009-10-01,1102.00,1173.70,1102.00,1167.00,1166.35,3074254.0,35463.78
2009-10-05,1152.00,1165.90,1136.60,1143.00,1140.55,919832.0,10581.13
2009-10-06,1149.80,1157.20,1132.10,1143.30,1144.90,627957.0,7185.90
2009-10-07,1153.80,1160.70,1140.00,1141.45,1141.60,698216.0,8032.98
...,...,...,...,...,...,...,...
2018-12-31,178.10,179.00,174.35,175.00,174.80,761462.0,1343.75
2019-01-01,175.00,176.40,174.15,175.15,175.75,381570.0,669.16
2019-01-02,175.80,176.20,171.00,172.35,172.40,722532.0,1251.85
2019-01-03,172.80,175.70,171.50,172.00,172.00,698190.0,1212.34
2019-01-04,172.05,174.95,172.05,174.55,174.55,431122.0,749.99

In [7]:
from iexfinance.refdata import get_symbols
from iexfinance.stocks import Stock

token_api = "sk_aa0a04e24b874ad8bbdb7132fba261db"
token_api = "pk_00d4e5f9cbdd44e78cfb6f504be796d0"
a = Stock("PG", token=token_api)
a.get_quote()

IEXQueryError: An error occurred while making the query (402): Your account does not have the relevant IEX Cloud data bundle add-on for this data. Buy data bundle add-ons at https://iexcloud.io/console/manage-plan.

In [31]:
import os
import pyEX as p

os.environ["IEX_TOKEN"] = "sk_aa0a04e24b874ad8bbdb7132fba261db"
os.environ["IEX_API_KEY"] = "sk_aa0a04e24b874ad8bbdb7132fba261db"
c = p.Client()

In [32]:
# c.chartDF('AAPL').head()

In [15]:
import os
os.environ["QUANDL_API_KEY"] = "Wi5xJFnD9bwKLwazVpvm"
PG = wb.DataReader('PG', 'quandl', start='2015-1-1')

In [18]:
PG[["Open", "High", "Low", "Close", "AdjClose"]]

             Open    High      Low  Close   AdjClose
Date
2018-03-27  76.53  78.440  76.3000  77.79  77.790000
2018-03-26  76.57  76.870  76.0200  76.41  76.410000
2018-03-23  76.79  77.180  75.8050  75.91  75.910000
2018-03-22  76.83  77.520  76.3700  76.41  76.410000
2018-03-21  78.05  78.240  76.8800  77.04  77.040000
...           ...     ...      ...    ...        ...
2015-01-08  90.48  91.225  90.1300  91.10  82.792868
2015-01-07  89.94  90.370  89.5626  90.07  81.856790
2015-01-06  90.31  90.560  89.2600  89.60  81.429648
2015-01-05  90.23  91.000  89.8500  90.01  81.802262
2015-01-02  90.84  91.000  89.9200  90.44  82.193051

[813 rows x 5 columns]

In [19]:
PG.head()

,Open,High,Low,Close,Volume,ExDividend,SplitRatio,AdjOpen,AdjHigh,AdjLow,AdjClose,AdjVolume
Date,,,,,,,,,,,,
2018-03-27,76.53,78.44,76.300,77.79,11257559.0,0.0,1.0,76.53,78.44,76.300,77.79,11257559.0
2018-03-26,76.57,76.87,76.020,76.41,11959444.0,0.0,1.0,76.57,76.87,76.020,76.41,11959444.0
2018-03-23,76.79,77.18,75.805,75.91,11626422.0,0.0,1.0,76.79,77.18,75.805,75.91,11626422.0
2018-03-22,76.83,77.52,76.370,76.41,10396180.0,0.0,1.0,76.83,77.52,76.370,76.41,10396180.0
2018-03-21,78.05,78.24,76.880,77.04,9776002.0,0.0,1.0,78.05,78.24,76.880,77.04,9776002.0

In [20]:
PG.tail()

,Open,High,Low,Close,Volume,ExDividend,SplitRatio,AdjOpen,AdjHigh,AdjLow,AdjClose,AdjVolume
Date,,,,,,,,,,,,
2015-01-08,90.48,91.225,90.1300,91.10,6831408.0,0.0,1.0,82.229404,82.906469,81.911319,82.792868,6831408.0
2015-01-07,89.94,90.370,89.5626,90.07,5986899.0,0.0,1.0,81.738645,82.129434,81.395659,81.856790,5986899.0
2015-01-06,90.31,90.560,89.2600,89.60,7791010.0,0.0,1.0,82.074905,82.302109,81.120652,81.429648,7791010.0
2015-01-05,90.23,91.000,89.8500,90.01,8626143.0,0.0,1.0,82.002200,82.701986,81.656851,81.802262,8626143.0
2015-01-02,90.84,91.000,89.9200,90.44,7255394.0,0.0,1.0,82.556576,82.701986,81.720468,82.193051,7255394.0

## Simple Rate of Return

$$
\frac{P_1 - P_0}{P_0} = \frac{P_1}{P_0} - 1
$$

In [23]:
PG['simple_return'] = (PG['Close'] / PG['Close'].shift(1)) - 1
print(PG['simple_return'])

Date
2018-03-27         NaN
2018-03-26   -0.017740
2018-03-23   -0.006544
2018-03-22    0.006587
2018-03-21    0.008245
                ...
2015-01-08    0.009418
2015-01-07   -0.011306
2015-01-06   -0.005218
2015-01-05    0.004576
2015-01-02    0.004777
Name: simple_return, Length: 813, dtype: float64